# Generated by Django 4.2 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_userprofile_hide_quickstart"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("zh-hans", "Chinese")],
                default="en",
                help_text="Set the default language for the web interface.",
                max_length=7,
                verbose_name="Web Interface Language",
            ),
        ),
    ]